# Generated by Django 3.2.5 on 2021-08-18 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainmenu', '0004_submenu_mainmenu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainmenu',
            name='has_submenu',
            field=models.IntegerField(default=None),
        ),
    ]
